name: Android Build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build with Buildozer
        uses: ArtemGr/buildozer-action@v1
        with:
          buildozer_version: master
          command: buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: CultivoEfectivo-APK
          path: bin/*.apk
