name: Android Build
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip build-essential libffi-dev setup-tools libssl-dev
          pip3 install --user --upgrade buildozer cython
      - name: Build APK
        run: |
          export PATH=$PATH:$HOME/.local/bin
          yes | buildozer android debug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CultivoEfectivo-APK
          path: bin/*.apk
